"""24/10/15-16:33:14

Revision ID: 0db377dc5d25
Revises: bd80b8299fe2
Create Date: 2024-10-15 16:33:17.995722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db377dc5d25'
down_revision: Union[str, None] = 'bd80b8299fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
